name: urbanization-score

services:
  urbanization-score:
    container_name: urbanization-score
    image: linstar666/urbanization-score:latest
    ports:
      - "3332:3333" # 将容器的 3333 端口映射到主机的 3332 端口
    volumes:
      # 持久化 SQLite 数据库文件/上传文件/日志文件
      - db_score:/app/db
    restart: unless-stopped # 保持 Docker 容器的运维状态，除非手动停止
    environment:
      DATABASE_URL: "file:../../db/urbanization.db" # 这确保了运行时容器内的 DATABASE_URL 环境变量被设置

volumes:
  db_score: # 定义一个命名卷用于数据库持久化 