packages:
  - frontend
  - backend
  - electron
  - loading-frontend
  - common
  - doc/*
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - electron
  - electron-winstaller
  - es5-ext
  - esbuild
  - prisma
  - sqlite3
